#!/bin/bash

echo "메일 전송 프로그램입니다."
echo "번호를 입력하세요"
echo -n "1. 모든 사용자에게 메세지 전달(ADMIN MODE)\n"

2. 특정 사용자에게 메세지 전달 \n

3. 현재 메세지 수신 설정을 확인 \n:"
read setting

if [ $setting==1 ]
then

echo -n "메세지를 입력하시오 : "
read message
sudo wall "$message"

 fi
 
