#!/bin/bash

echo "메일 전송 프로그램입니다."
echo "번호를 입력하세요"
read -n 1 -p "1. 모든 사용자에게 메세지 전달(ADMIN MODE)\n

2. 특정 사용자에게 메세지 전달 \n

3. 현재 메세지 수신 설정을 확인 \n"

if [ ${REPLY} = 1 ];then

read -n 1 -p "메세지를 입력하세요:" message
wall "$message"

 fi
 
