#!/bin/bash
# 메인 메뉴
cat << "EOF"
#       ### #     # #     # #     #    #     #    #    ### #           #####  #     #  #####  ####### ####### #     # 
#        #  ##    # #     #  #   #     ##   ##   # #    #  #          #     #  #   #  #     #    #    #       ##   ## 
#        #  # #   # #     #   # #      # # # #  #   #   #  #          #         # #   #          #    #       # # # # 
#        #  #  #  # #     #    #       #  #  # #     #  #  #           #####     #     #####     #    #####   #  #  # 
#        #  #   # # #     #   # #      #     # #######  #  #                #    #          #    #    #       #     # 
#        #  #    ## #     #  #   #     #     # #     #  #  #          #     #    #    #     #    #    #       #     # 
####### ### #     #  #####  #     #    #     # #     # ### #######     #####     #     #####     #    ####### #     #  
EOF
echo "-----------------------------------------------------------------------------"
echo "메일 전송 프로그램입니다."
echo "번호를 입력하세요"
echo "-----------------------------------------------------------------------------"
# 모든 사용자 메세지
echo -n "1. 모든 사용자에게 메세지 전달(ADMIN MODE ONLY)
2. 특정 사용자에게 메세지 전달 
3. 현재 메세지 수신 설정을 확인 
종료하려면 CTRL + C 키를 눌러주세요
-----------------------------------------------------------------------------
:"

read setting

if [ $setting -eq 1 ]
then
echo -n "메세지를 입력하시오 : "
read message

sudo wall "$message"

# 특정 사용자 메세지
elif [ $setting -eq 2 ]
then
echo "<특정 사용자에게 메일 전송>"
echo "(1) Talk / (2) Write
:"
read ans

if [ $ans -eq 1 ]
then
 echo "<talk 명령어>"
 echo "사용자의 hostname은 다음과 같습니다."
 hostname
 echo ""
 echo "수신자와 같은 시스템인가요?(Y/N)"

 read answer

if [[ $answer = [Yy]* ]]
then
 echo "수신자 ID: "

else
 echo "수신자 ID@hostname"

fi

read id1
talk id1

#write 명령어 사용
elif [ $ans -eq 2 ]
echo "<write 명령어>"
then
 echo -n "수신자 ID: "
 read id2
# 욕설감지
echo -n "*비속어 사용시 프로그램이 종료됩니다*
메세지를 입력하시오 :"
read chat

if  [[ "$chat" =~ "바보" ]]
then
echo "비속어 감지!
프로그램을 종료합니다"

else
write $id2
$chat
fi
fi

# 메세지 수신상태 확인
elif [ $setting -eq 3 ]
echo "메세지 수신상태를 확인합니다"
then
susin=`mesg`
if [[ "$susin" =~ "y" ]]
then
echo "메세지 수신이 허용 상태입니다!"

elif [[ "$susin" =~ "n" ]]
then
echo "메세지 수신이 거부 상태입니다!"
fi
fi
